import 'package:flutter/material.dart';
import '../helpers/user_info.dart';
import '../model/antrian.dart';
import '../model/poli.dart';
import '../service/antrian_service.dart';
import '../service/poli_service.dart';
import '../widget/animated_pressable.dart';
import '../widget/smooth_page_route.dart';
import '../widget/staggered_entrance.dart';
import 'antrian_detail.dart';

class AntrianForm extends StatefulWidget {
  const AntrianForm({super.key});

  @override
  State<AntrianForm> createState() => _AntrianFormState();
}

class _AntrianFormState extends State<AntrianForm> {
  final _formKey = GlobalKey<FormState>();
  final _namaPasienCtrl = TextEditingController();
  final _nomorRmCtrl = TextEditingController();
  final _nomorTeleponCtrl = TextEditingController();
  final _tanggalCtrl = TextEditingController();
  final _keluhanCtrl = TextEditingController();

  List<Poli> _poliList = [];
  Poli? _selectedPoli;
  bool _isLoadingPoli = true;
  bool _isSubmitting = false;
  String _estimatedNomor = "";

  @override
  void initState() {
    super.initState();
    final today = DateTime.now();
    _tanggalCtrl.text =
        "${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}";
    _loadInitialData();
  }

  @override
  void dispose() {
    _namaPasienCtrl.dispose();
    _nomorRmCtrl.dispose();
    _nomorTeleponCtrl.dispose();
    _tanggalCtrl.dispose();
    _keluhanCtrl.dispose();
    super.dispose();
  }

  Future<void> _loadInitialData() async {
    // Fill with current patient profile if not admin
    final isAdmin = await UserInfo().isAdmin();
    if (!isAdmin) {
      final nama = await UserInfo().getNama();
      final username = await UserInfo().getUsername();
      final phone = await UserInfo().getNomorTelepon();
      final rm = await UserInfo().getNomorRm();

      if (nama != null && nama.isNotEmpty) {
        _namaPasienCtrl.text = nama;
      } else if (username != null && username.isNotEmpty) {
        _namaPasienCtrl.text = username;
      }

      if (phone != null && phone.isNotEmpty) {
        _nomorTeleponCtrl.text = phone;
      }

      if (rm != null && rm.isNotEmpty) {
        _nomorRmCtrl.text = rm;
      }
    }

    try {
      final polis = await PoliService().listData();
      if (mounted) {
        setState(() {
          _poliList = polis;
          _isLoadingPoli = false;
          if (polis.isNotEmpty) {
            _selectedPoli = polis.first;
            _updateEstimatedNumber();
          }
        });
      }
    } catch (_) {
      if (mounted) {
        setState(() => _isLoadingPoli = false);
      }
    }
  }

  Future<void> _updateEstimatedNumber() async {
    if (_selectedPoli?.id != null && _tanggalCtrl.text.isNotEmpty) {
      final nextNumber = await AntrianService().generateNomorAntrian(
        _selectedPoli!.id!,
        _tanggalCtrl.text.trim(),
      );
      if (mounted) {
        setState(() => _estimatedNomor = nextNumber);
      }
    }
  }

  Future<void> _selectDate() async {
    final now = DateTime.now();
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: now,
      firstDate: now,
      lastDate: now.add(const Duration(days: 30)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: Color(0xFF0F766E),
              onPrimary: Colors.white,
              onSurface: Color(0xFF1C1C1E),
            ),
          ),
          child: child!,
        );
      },
    );

    if (picked != null) {
      setState(() {
        _tanggalCtrl.text =
            "${picked.year}-${picked.month.toString().padLeft(2, '0')}-${picked.day.toString().padLeft(2, '0')}";
      });
      _updateEstimatedNumber();
    }
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedPoli == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          backgroundColor: Color(0xFFFF3B30),
          content: Text("Silakan pilih poliklinik tujuan."),
        ),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final now = TimeOfDay.now();
      final timeStr =
          "${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}";

      final antrianBaru = Antrian(
        nomorAntrian: "", // will be generated by service
        idPoli: _selectedPoli!.id ?? "1",
        namaPoli: _selectedPoli!.namaPoli,
        namaPasien: _namaPasienCtrl.text.trim(),
        nomorRm: _nomorRmCtrl.text.trim().isNotEmpty ? _nomorRmCtrl.text.trim() : "RM-BARU",
        nomorTelepon: _nomorTeleponCtrl.text.trim(),
        tanggal: _tanggalCtrl.text.trim(),
        waktu: timeStr,
        keluhan: _keluhanCtrl.text.trim(),
        status: "Menunggu",
      );

      final saved = await AntrianService().simpan(antrianBaru);

      if (!mounted) return;
      setState(() => _isSubmitting = false);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          backgroundColor: const Color(0xFF34C759),
          content: Text("Nomor antrian berhasil diambil: ${saved.nomorAntrian}"),
        ),
      );

      // Navigate to digital ticket detail
      Navigator.pushReplacement(
        context,
        SmoothPageRoute(page: AntrianDetail(antrian: saved)),
      );
    } catch (e) {
      if (!mounted) return;
      setState(() => _isSubmitting = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          backgroundColor: const Color(0xFFFF3B30),
          content: Text("Gagal mengambil antrian: $e"),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF2F2F7),
      appBar: AppBar(
        title: const Text("Ambil Antrian Berobat"),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Ticket Preview Banner
              if (_estimatedNomor.isNotEmpty)
                StaggeredEntrance(
                  index: 0,
                  child: Container(
                    margin: const EdgeInsets.only(bottom: 18),
                    padding: const EdgeInsets.all(18),
                    decoration: BoxDecoration(
                      color: const Color(0xFF0F766E),
                      borderRadius: BorderRadius.circular(18),
                      boxShadow: [
                        BoxShadow(
                          color: const Color(0xFF0F766E).withValues(alpha: 0.2),
                          blurRadius: 12,
                          offset: const Offset(0, 4),
                        ),
                      ],
                    ),
                    child: Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                          decoration: BoxDecoration(
                            color: Colors.white,
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Text(
                            _estimatedNomor,
                            style: const TextStyle(
                              fontSize: 22,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF0F766E),
                              letterSpacing: -0.5,
                            ),
                          ),
                        ),
                        const SizedBox(width: 14),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text(
                                "Perkiraan Nomor Antrian",
                                style: TextStyle(
                                  color: Colors.white70,
                                  fontSize: 12,
                                  letterSpacing: -0.2,
                                ),
                              ),
                              const SizedBox(height: 2),
                              Text(
                                _selectedPoli?.namaPoli ?? "Poliklinik",
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 15,
                                  fontWeight: FontWeight.bold,
                                  letterSpacing: -0.3,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),

              // Form Container
              StaggeredEntrance(
                index: 1,
                child: Container(
                  padding: const EdgeInsets.all(22),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(color: const Color(0xFFE5E5EA), width: 0.8),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withValues(alpha: 0.03),
                        blurRadius: 12,
                        offset: const Offset(0, 3),
                      ),
                    ],
                  ),
                  child: Form(
                    key: _formKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        const Text(
                          "Pilih Poliklinik & Jadwal",
                          style: TextStyle(
                            fontSize: 15.5,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF1C1C1E),
                            letterSpacing: -0.3,
                          ),
                        ),
                        const SizedBox(height: 14),

                        // Poli Dropdown
                        _isLoadingPoli
                            ? const Center(
                                child: Padding(
                                  padding: EdgeInsets.all(12),
                                  child: CircularProgressIndicator(color: Color(0xFF0F766E)),
                                ),
                              )
                            : DropdownButtonFormField<Poli>(
                                initialValue: _selectedPoli,
                                decoration: const InputDecoration(
                                  labelText: "Poliklinik Spesialis",
                                  prefixIcon: Icon(Icons.meeting_room_rounded,
                                      color: Color(0xFF0F766E)),
                                ),
                                items: _poliList.map((p) {
                                  return DropdownMenuItem<Poli>(
                                    value: p,
                                    child: Text(
                                      p.namaPoli,
                                      style: const TextStyle(
                                        fontSize: 14,
                                        fontWeight: FontWeight.w500,
                                        color: Color(0xFF1C1C1E),
                                      ),
                                    ),
                                  );
                                }).toList(),
                                onChanged: (val) {
                                  setState(() => _selectedPoli = val);
                                  _updateEstimatedNumber();
                                },
                                validator: (val) => val == null ? "Pilih poliklinik" : null,
                              ),

                        const SizedBox(height: 14),

                        // Date field
                        TextFormField(
                          controller: _tanggalCtrl,
                          readOnly: true,
                          onTap: _selectDate,
                          decoration: InputDecoration(
                            labelText: "Tanggal Kunjungan",
                            prefixIcon: const Icon(Icons.calendar_today_rounded,
                                color: Color(0xFF0F766E)),
                            suffixIcon: IconButton(
                              icon: const Icon(Icons.edit_calendar_rounded,
                                  color: Color(0xFF0F766E)),
                              onPressed: _selectDate,
                            ),
                          ),
                          validator: (val) =>
                              val == null || val.trim().isEmpty ? "Tanggal wajib diisi" : null,
                        ),

                        const SizedBox(height: 22),
                        const Divider(height: 1, color: Color(0xFFE5E5EA)),
                        const SizedBox(height: 18),

                        const Text(
                          "Informasi Pasien",
                          style: TextStyle(
                            fontSize: 15.5,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF1C1C1E),
                            letterSpacing: -0.3,
                          ),
                        ),
                        const SizedBox(height: 14),

                        // Nama Pasien
                        TextFormField(
                          controller: _namaPasienCtrl,
                          decoration: const InputDecoration(
                            labelText: "Nama Lengkap Pasien",
                            hintText: "Contoh: Budi Santoso",
                            prefixIcon: Icon(Icons.person_rounded, color: Color(0xFF0F766E)),
                          ),
                          validator: (val) =>
                              val == null || val.trim().isEmpty ? "Nama pasien wajib diisi" : null,
                        ),
                        const SizedBox(height: 14),

                        // Nomor RM
                        TextFormField(
                          controller: _nomorRmCtrl,
                          decoration: const InputDecoration(
                            labelText: "Nomor Rekam Medis (RM)",
                            hintText: "Contoh: RM-2024-001 (Opsional)",
                            prefixIcon:
                                Icon(Icons.medical_information_rounded, color: Color(0xFF0F766E)),
                          ),
                        ),
                        const SizedBox(height: 14),

                        // Nomor Telepon
                        TextFormField(
                          controller: _nomorTeleponCtrl,
                          keyboardType: TextInputType.phone,
                          decoration: const InputDecoration(
                            labelText: "Nomor Telepon / WhatsApp",
                            hintText: "Contoh: 081234567890",
                            prefixIcon: Icon(Icons.phone_rounded, color: Color(0xFF0F766E)),
                          ),
                          validator: (val) {
                            if (val == null || val.trim().isEmpty) {
                              return "Nomor telepon wajib diisi";
                            }
                            if (val.trim().length < 8) {
                              return "Nomor telepon minimal 8 digit";
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 14),

                        // Keluhan
                        TextFormField(
                          controller: _keluhanCtrl,
                          maxLines: 3,
                          decoration: const InputDecoration(
                            labelText: "Keluhan / Gejala yang Dirasakan",
                            hintText: "Jelaskan secara singkat gejala yang dialami...",
                            prefixIcon:
                                Icon(Icons.chat_bubble_outline_rounded, color: Color(0xFF0F766E)),
                            alignLabelWithHint: true,
                          ),
                          validator: (val) =>
                              val == null || val.trim().isEmpty ? "Keluhan wajib diisi" : null,
                        ),

                        const SizedBox(height: 26),

                        // Submit Button
                        AnimatedPressable(
                          borderRadius: BorderRadius.circular(14),
                          onTap: _isSubmitting ? null : _handleSubmit,
                          child: Container(
                            height: 50,
                            decoration: BoxDecoration(
                              color: const Color(0xFF0F766E),
                              borderRadius: BorderRadius.circular(14),
                            ),
                            alignment: Alignment.center,
                            child: _isSubmitting
                                ? const SizedBox(
                                    width: 22,
                                    height: 22,
                                    child: CircularProgressIndicator(
                                      color: Colors.white,
                                      strokeWidth: 2.2,
                                    ),
                                  )
                                : Row(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: const [
                                      Icon(Icons.confirmation_number_rounded,
                                          color: Colors.white, size: 20),
                                      SizedBox(width: 8),
                                      Text(
                                        "Konfirmasi & Ambil Antrian",
                                        style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 15,
                                          fontWeight: FontWeight.w600,
                                          letterSpacing: -0.2,
                                        ),
                                      ),
                                    ],
                                  ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
